[phases.setup]
nixPkgs = ['python311', 'nodejs_18']

[phases.install]
cmds = [
  "npm install",
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "node server.js"
